{% set name = "dsnparse" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 90956235967569c875994adbad0928c347a1592b5fc8ecd9c1b1a20397dae697

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - dsnparse

about:
  home: http://github.com/Jaymon/dsnparse
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: parse dsn urls

extra:
  recipe-maintainers:
    - astrojuanlu
