# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: dsnparse
  version: "0.4.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/dsnparse-${{ version }}.tar.gz
  sha256: 301a251ef74832dccfb3535650b270749c8c7ef49437847a4cd3ed353b873ff2

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }},<4.0

tests:
  - python:
      imports:
        - dsnparse
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: parse dsn urls
  license: MIT
  license_file: LICENSE.txt
  homepage: http://github.com/Jaymon/dsnparse

extra:
  recipe-maintainers:
    - astrojuanlu
    - rxm7706
